import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

/**
 * Manages the Game Runner Webview Panel
 * This panel renders HTML/JS games generated by the AI directly inside VS Code.
 */
export class GameRunnerPanel {
    public static currentPanel: GameRunnerPanel | undefined;
    private readonly _panel: vscode.WebviewPanel;
    private readonly _extensionUri: vscode.Uri;
    private _disposables: vscode.Disposable[] = [];

    private constructor(panel: vscode.WebviewPanel, extensionUri: vscode.Uri, gameHtmlContent: string, workspaceRoot: string) {
        this._panel = panel;
        this._extensionUri = extensionUri;

        // Set the webview's initial html content
        this._update(gameHtmlContent, workspaceRoot);

        // Listen for when the panel is disposed
        this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

        // Handle messages from the webview (like console logs or errors)
        this._panel.webview.onDidReceiveMessage(
            message => {
                switch (message.command) {
                    case 'error':
                        vscode.window.showErrorMessage(`Game Error: ${message.text}`);
                        return;
                    case 'log':
                        console.log(`Game Log: ${message.text}`);
                        return;
                }
            },
            null,
            this._disposables
        );
    }

    public static createOrShow(extensionUri: vscode.Uri, gameFilePath: string, workspaceRoot: string) {
        const column = vscode.window.activeTextEditor
            ? vscode.window.activeTextEditor.viewColumn
            : undefined;

        let gameHtmlContent = '';
        try {
            gameHtmlContent = fs.readFileSync(gameFilePath, 'utf8');
        } catch (e: any) {
            vscode.window.showErrorMessage(`Failed to read game file: ${e.message}`);
            return;
        }

        // If we already have a panel, show it.
        if (GameRunnerPanel.currentPanel) {
            GameRunnerPanel.currentPanel._panel.reveal(column);
            GameRunnerPanel.currentPanel._update(gameHtmlContent, workspaceRoot);
            return;
        }

        // Otherwise, create a new panel.
        const panel = vscode.window.createWebviewPanel(
            'gameRunner',
            '🎮 Game Preview',
            column || vscode.ViewColumn.One,
            {
                // Enable javascript in the webview
                enableScripts: true,
                // Restrict the webview to only loading content from our extension's `assets` directory.
                // For a game engine, we want to allow local workspace assets.
                localResourceRoots: [vscode.Uri.file(workspaceRoot)]
            }
        );

        GameRunnerPanel.currentPanel = new GameRunnerPanel(panel, extensionUri, gameHtmlContent, workspaceRoot);
    }

    public dispose() {
        GameRunnerPanel.currentPanel = undefined;

        this._panel.dispose();

        while (this._disposables.length) {
            const x = this._disposables.pop();
            if (x) {
                x.dispose();
            }
        }
    }

    private _update(htmlContent: string, workspaceRoot: string) {
        const webview = this._panel.webview;
        
        // We need to rewrite local paths (like ./assets/texture.jpg) to use webview URIs
        // This regex looks for src="..." and href="..." and replaces relative paths.
        let patchedHtml = htmlContent;
        
        // Very basic path patching (assuming assets are in /assets folder or relative)
        patchedHtml = patchedHtml.replace(/(src|href)=["']([^"']+)["']/gi, (match, p1, p2) => {
            // Ignore http/https links and data URIs
            if (p2.startsWith('http') || p2.startsWith('data:')) {
                return match;
            }
            
            // Convert relative path to absolute workspace path, then to webview URI
            try {
                const absolutePath = path.resolve(workspaceRoot, p2.replace(/^\.\//, ''));
                if (fs.existsSync(absolutePath)) {
                    const webviewUri = webview.asWebviewUri(vscode.Uri.file(absolutePath));
                    return `${p1}="${webviewUri}"`;
                }
            } catch (e) {
                // ignore
            }
            return match;
        });

        // Inject Error/Log interceptor script and <base> tag into the <head>
        const baseUri = webview.asWebviewUri(vscode.Uri.file(workspaceRoot)).toString();
        const interceptorScript = `
            <base href="${baseUri}/">
            <script>
                const vscode = acquireVsCodeApi();
                window.onerror = function(message, source, lineno, colno, error) {
                    vscode.postMessage({ command: 'error', text: message + ' at line ' + lineno });
                };
                const originalLog = console.log;
                console.log = function(...args) {
                    vscode.postMessage({ command: 'log', text: args.join(' ') });
                    originalLog.apply(console, args);
                };
            </script>
        `;

        if (patchedHtml.includes('<head>')) {
            patchedHtml = patchedHtml.replace('<head>', `<head>\n${interceptorScript}`);
        } else {
            patchedHtml = `${interceptorScript}\n${patchedHtml}`;
        }

        this._panel.webview.html = patchedHtml;
    }
}
